---
- name: Managers nodes joining the cluster
  become: True
  command: 
    cmd: "docker swarm join --token {{hostvars[groups.leader[0]]['swarm_manager_join_token']['stdout']}} {{hostvars[groups.leader[0]]['ansible_default_ipv4']['address']}}:{{advertise_port}}"
  when: inventory_hostname in groups.managers and inventory_hostname != groups.leader[0]
...